### ISSUE TITLE
Creating a todo should not return data int he response. 

### ISSUE THREAD

**Issue by vaibhavkaul** [srv89/karya#3]
A simple status code 200 with possibly an id should be enough

**Comment by srv89** [comment]
The only reason I have return the whole payload is because I read a couple of APIs like Stripe and Square. When they create a resource they return the whole payload. Also if a user creates a resource and then wants to use that data to perform any operation he/she would have to do a GET which would be unnecessary (Even though this is a basic app, it might slow down the app). 

[Square API](https://docs.connect.squareup.com/api/connect/v1/#post-employees)
[Stripe API](https://stripe.com/docs/api#create_charge)

**Comment by vaibhavkaul** [comment]
> Also if a user creates a resource and then wants to use that data to perform any operation he/she would have to do a GET which would be unnecessary (Even though this is a basic app, it might slow down the app).

It would go a long way in keeping the UI easy. Ui should maintain as little state as possible. 

> Is there a particular reason we should be just returning 200 with id ? Also I would prefer returning 201.

201 is better you are right.

**Comment by srv89** [comment]
Ok. I still have to look into POST vs PUT vs PATCH.

**Comment by vaibhavkaul** [comment]
I closed the PUT issue.

Basically since this is an API post is fine.

e.g. 

It is ok to `POST` to `/todos` to create a TODO

a `PUT` would be to `/todos/{id}`

certain resources can be created after creation of a DB record.

**Comment by srv89** [comment]
For now keeping full response payload.
